# Generated by Django 6.0.7 on 2026-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_remove_project_technologies_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
