# Generated by Django 6.0.7 on 2026-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_profile_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
