# Generated by Django 6.1 on 2026-08-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_alter_project_github_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
