# Generated by Django 6.1 on 2026-08-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_delete_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
