# Generated by Django 6.1 on 2026-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='emailsubject',
            field=models.TextField(default='blank mail', max_length=100),
        ),
    ]
