# Generated by Django 6.1 on 2026-08-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_contact_emailsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailsubject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobilenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
