# Generated by Django 6.1 on 2026-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_alter_contact_emailsubject_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailaddress',
            field=models.URLField(max_length=50),
        ),
    ]
