# Generated by Django 6.1 on 2026-08-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_alter_contact_emailaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
