# Generated by Django 6.1 on 2026-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
